# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipcprobe" do
  version "0.3.0"

  on_macos do
    sha256 "f6899da96c6d60bee530a4fc437f02a54a1c1f2738e7e61f726e5fbcf05d4637"
    url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "618f594d7e6cb2b6a9b4de9977529c7345b23e4e7e78039923d93b6a01a230b5"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "42c51c89ac35b90711bade8c5f024d20561e4443c197ca9ed2d34935f73b95a8"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_amd64.tar.gz"
    end
  end

  name "ipcprobe"
  desc "Discover and reconfigure TVT/OEM (e.g. DVC) IP cameras on a LAN — a cross-platform IPTool replacement"
  homepage "https://github.com/AlexandruIspas659/ipcprobe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipcprobe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipcprobe"]
    end
  end

  # No zap stanza required
end
