# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipcprobe" do
  version "0.2.0"

  on_macos do
    sha256 "3396969f62975bf3a5186ced83cb2da8f8f28650db25074835901d74b4cb733f"
    url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "f155622735e19c7423e7e1c5a28a4151a76e84c59b2f3c5e39bdc5a53ed4ddc6"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f7359bfba2b9f5fc5815660eb5eb5e09ec938ca45723e4ac54d133a5d51d4df"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_amd64.tar.gz"
    end
  end

  name "ipcprobe"
  desc "Discover and reconfigure TVT/OEM (e.g. DVC) IP cameras on a LAN — a cross-platform IPTool replacement"
  homepage "https://github.com/AlexandruIspas659/ipcprobe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipcprobe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipcprobe"]
    end
  end

  # No zap stanza required
end
