# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipcprobe" do
  version "0.3.1"

  on_macos do
    sha256 "cf4689e2e8c2cf0fda04c75363e5a0669e5e4f0da0730e879d1f7e932d2428a2"
    url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "f86c348d6b0831e0ad6509d69934d6f058d71cc94583b36675a2fc8db5dfc206"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed8ab870ffe7044469b8cd7dc012392a28b0975f1ca938d66f894b530f59abb5"
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v#{version}/ipcprobe_linux_amd64.tar.gz"
    end
  end

  name "ipcprobe"
  desc "Discover and reconfigure TVT/OEM (e.g. DVC) IP cameras on a LAN — a cross-platform IPTool replacement"
  homepage "https://github.com/AlexandruIspas659/ipcprobe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipcprobe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipcprobe"]
    end
  end

  # No zap stanza required
end
