# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipcprobe < Formula
  desc "Discover and reconfigure TVT/OEM (e.g. DVC) IP cameras on a LAN — a cross-platform IPTool replacement"
  homepage "https://github.com/AlexandruIspas659/ipcprobe"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v0.1.1/ipcprobe_darwin_all.tar.gz"
    sha256 "14b575ba6c248440d19d8f65640147ccc6edb8e8609ef49e5ad15b8c14c14d44"

    define_method(:install) do
      bin.install "ipcprobe"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v0.1.1/ipcprobe_linux_amd64.tar.gz"
      sha256 "9822c3c53e0d3f74ded1e5e9d1d6e461b9c8f4b688a1bb38ab4c1b8da582a851"
      define_method(:install) do
        bin.install "ipcprobe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexandruIspas659/ipcprobe/releases/download/v0.1.1/ipcprobe_linux_arm64.tar.gz"
      sha256 "7aa6a9319d509d1121173bad957f224530c8b1e1d9f4ce0495f5854f4433b230"
      define_method(:install) do
        bin.install "ipcprobe"
      end
    end
  end

  test do
    assert_match "ipcprobe", shell_output("#{bin}/ipcprobe --version")
  end
end
